### ISSUE TITLE
References to non-existent personal local paths in the source code lead to errors

### ISSUE THREAD

**Issue by leeyiding** [neu-vi/HOI-Diff#6]
Some personal local paths are referenced in these places, resulting in an error being reported when the corresponding files cannot be found during the training process.
https://github.com/neu-vi/HOI-Diff/blob/edb4e7092e6935d8cbc29ba59ebc511b267e1acb/utils/utils.py#L127-L128
https://github.com/neu-vi/HOI-Diff/blob/edb4e7092e6935d8cbc29ba59ebc511b267e1acb/utils/utils.py#L104-L105

```bash
python -m train.hoi_diff --save_dir ./save/behave_enc_512 --dataset behave --save_interval 1000 --num_steps 20000 --arch trans_enc --batch_size 32
```

```
Traceback (most recent call last):
  File "/root/anaconda3/envs/t2hoi/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/t2hoi/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/HOI-Diff/train/hoi_diff.py", line 73, in <module>
    main()
  File "/root/HOI-Diff/train/hoi_diff.py", line 50, in main
    model, diffusion = create_model_and_diffusion(args, data, ModelClass=HOIDiff, DiffusionClass=LocalMotionDiffusion)
  File "/root/HOI-Diff/utils/model_util.py", line 58, in create_model_and_diffusion
    diffusion = create_gaussian_diffusion(args, diff_steps, DiffusionClass)
  File "/root/HOI-Diff/utils/model_util.py", line 130, in create_gaussian_diffusion
    return DiffusionClass(
  File "/root/HOI-Diff/diffusion/gaussian_diffusion.py", line 1779, in __init__
    self.normalizer = MotionNormalizerTorch()
  File "/root/HOI-Diff/utils/utils.py", line 127, in __init__
    mean = np.load("/work/vig/xiaogangp/codes/guided-motion-diffusion/dataset/Behave_global/Mean_global.npy")
  File "/root/anaconda3/envs/t2hoi/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/work/vig/xiaogangp/codes/guided-motion-diffusion/dataset/Behave_global/Mean_global.npy'
```

**Comment by xiaogangpeng** [comment]
Sorry for the bugs, we have fixed this and update the repo.
