### ISSUE TITLE
Failed to load dataset correctly when training APDM

### ISSUE THREAD

**Issue by leeyiding** [neu-vi/HOI-Diff#7]
Hello, I downloaded the dataset from Google Drive and organized the directory structure correctly according to the instructions of README, but there was an error in the training APDM. It seems that the dataset was not loaded correctly.
![image](https://github.com/neu-vi/HOI-Diff/assets/49098278/f76c0390-da31-4f4e-9707-82bc83a2255c)

```bash
python -m train.train_affordance --save_dir ./save/afford_pred --dataset behave --save_interval 1000 --num_steps 20000 --batch_size 32 --diffusion_steps 500
```
```
Reading ././dataset/behave_opt.txt
Loading dataset t2m_behave ...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 972/972 [00:03<00:00, 272.07it/s]
Traceback (most recent call last):
  File "/root/anaconda3/envs/t2hoi/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/t2hoi/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/HOI-Diff/train/train_affordance.py", line 64, in <module>
    main()
  File "/root/HOI-Diff/train/train_affordance.py", line 49, in main
    data = get_dataset_loader(data_conf)
  File "/root/HOI-Diff/data_loaders/get_data.py", line 63, in get_dataset_loader
    dataset = get_dataset(conf)
  File "/root/HOI-Diff/data_loaders/get_data.py", line 50, in get_dataset
    dataset = DATA(split=conf.split,
  File "/root/HOI-Diff/data_loaders/behave/data/dataset.py", line 567, in __init__
    assert len(self.t2m_dataset) > 1, 'You loaded an empty dataset, ' \
AssertionError: You loaded an empty dataset, it is probably because your data dir has only texts and no motions.
To train and evaluate MDM you should get the FULL data as described in the README file.
```

The process of training HOI-DM was successful.

**Comment by xiaogangpeng** [comment]
It seems that you used the old version of data on Google Drive, so the name is not matched when loading data. Please download the latest data through the link in README. Feel free to let us know if you have any questions.
