### ISSUE TITLE
Some bug in generate process

### ISSUE THREAD

**Issue by MuHe97** [neu-vi/HOI-Diff#9]
Thank you for all your contribution! However, when I reached the fifth part, I encountered the following error:
```
Traceback (most recent call last):
  File "/root/anaconda3/envs/mdm/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/mdm/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/hemu/HOI-Diff/sample/local_generate_obj.py", line 379, in <module>
    main()
  File "/root/hemu/HOI-Diff/sample/local_generate_obj.py", line 176, in main
    sample = sample_fn(
  File "/root/hemu/HOI-Diff/diffusion/gaussian_diffusion.py", line 730, in p_sample_loop
    for i, sample in enumerate(self.p_sample_loop_progressive(
  File "/root/hemu/HOI-Diff/diffusion/gaussian_diffusion.py", line 817, in p_sample_loop_progressive
    out = sample_fn(
  File "/root/hemu/HOI-Diff/diffusion/gaussian_diffusion.py", line 625, in p_sample
    out["mean"] = self.condition_mean(
  File "/root/hemu/HOI-Diff/diffusion/gaussian_diffusion.py", line 1797, in condition_mean
    return super().condition_mean(self._wrap_model(cond_fn), *args, **kwargs)
  File "/root/hemu/HOI-Diff/diffusion/gaussian_diffusion.py", line 462, in condition_mean
    loss, grad, loss_list = cond_fn(x,
  File "/root/hemu/HOI-Diff/diffusion/gaussian_diffusion.py", line 1885, in __call__
    return self.model(x, new_ts, **kwargs)
  File "/root/hemu/HOI-Diff/sample/condition.py", line 54, in __call__
    loss, grad, loss_list = self.gradients(x, t, self.afford_sample, y['obj_points'], y['obj_normals'])
  File "/root/hemu/HOI-Diff/sample/condition.py", line 155, in gradients
    grad = torch.autograd.grad([loss_sum], [x])[0]
  File "/root/anaconda3/envs/mdm/lib/python3.8/site-packages/torch/autograd/__init__.py", line 303, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [196, 512, 3]] is at version 10; expected version 9 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```
could you please help to handle this bug in the generate process?

**Comment by DonlynLee** [comment]
Hello, I have encountered the same problem just now. Have you solved it out?

**Comment by xiaogangpeng** [comment]
> Hi, did you use "with torch.autograd.set_detect_anomaly(True):" to check where the error occurs?

**Comment by DonlynLee** [comment]
Haven't. Maybe the problem comes from pytorch version? My torch version is 1.11.0

**Comment by xiaogangpeng** [comment]
> Haven't. Maybe the problem comes from pytorch version? My torch version is 1.11.0

Most likely! You can test the version of torch 1.7.1+cu110.

**Comment by MuHe97** [comment]
Thank you ! It works!!
